<?php if(!Mage::getSingleton('customer/session')->isLoggedIn()){
	$title=Mage::getStoreConfig('bluethink/bluethink_group/bluethink_input',Mage::app()->getStore());
	$flag=Mage::getStoreConfig('bluethink/bluethink_group/bluethink_select',Mage::app()->getStore());
		$contents=Mage::getStoreConfig('bluethink/bluethink_group/bluethink_textarea',Mage::app()->getStore());
 $alphabet = "abcdefghijklmnopqrstuwxyzABCDEFGHIJKLMNOPQRSTUWXYZ0123456789";
    $pass = '';                           //password is a string
    $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
    for ($i = 0; $i <8; $i++) {
        $n = mt_rand(0, $alphaLength);    
        $pass = $pass.$alphabet[$n];      //append a random character
    }
	//echo $fldddag;

if($flag){?>

<div id="popForm" style = "display:none">
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('popup/css/popup.css');?>"/>
<div class="popup_container sign_in_modal" id="transparent_bg">
	<div style="width:660px;" class="overlay-inner-bg" id="content">
		<a href="javascript:void(0)" onclick="closeSignup()" class="cross_popup">  </a>
		<div class="reg_msg">
			<?php $imagePath = Mage::getStoreConfig('bluethink/bluethink_group/logo') ; ?>
			<?php if(isset($imagePath) and $imagePath!=""){ ?>
			<img width="288px" height="171px" class="reg_msg_img" src="<?php echo Mage::getBaseUrl('media') . 'theme/'.Mage::getStoreConfig('bluethink/bluethink_group/logo'); ?>">
           <?php }else{ ?>
              <img width="288px" height="171px" class="reg_msg_img" src="<?php echo $this->getSkinUrl('popup/images/no_image.jpg'); ?>">
           <?php } ?>
				</div>
			
	<div style="width:300px;" class="left_block left_block_new">
		<h2>Register</h2>
	<div class="sign_signup_form">
	<form rel="signupBox" action="" method="post" id="signup-form" name="myFrom">
		<input type="hidden" value="" name="csrf_token">					
		<span style="color:#990000; font-size:14px;"></span>
		<div class="error" id="error_msg"></div>
	<ul>
		<li>  
			<input type="text" autocomplete="off" maxlength="100" id="email" name="email" value="" placeholder="Email ID - eg: bluethink@domain.com"  class="required-entry validate-email"><br>
			<div style="display:none" class="validation-advice" id="emailError">Please enter a valid email address. For example bluethink@domain.com</div>
				<span id="email" class="errormsz_email"></span>
		</li>
		<li>
		<div class="form_field_left">
			<input type="text" autocomplete="off" id="firstname" maxlength="35" name="firstname" value="" placeholder="First Name" class="required-entry">
			<span id="firstname" class="error_msg"></span>
		<div style="display:none" class="validation-advice" id="fnameError">Please use letters only (a-z or A-Z) in this field.</div>
		</div>
		<div class="form_field_right">
			<input type="text" autocomplete="off" id="lastname" maxlength="35" name="lastname" value="" placeholder="Last Name" class="required-entry">
			<span id="lastname" class="error_msg"></span>
		<div style="display:none" class="validation-advice" id="lnameError">Please use letters only (a-z or A-Z) in this field.</div>
		</div>
		<div class="clearfix"></div>
		</li>
		<li>
			<input type="text" autocomplete="off" name="mobile" id="mobile" class="login_input validate-number required-entry" value="" placeholder="Mobile - eg: 9800000000" pattern="[0-9]*" maxlength="10"><br>
			<span id="mobile" class="error_msg"></span>
		<div style="display:none" class="validation-advice" id="mobileError">Enter correct mobile number (Eg:9800000000)</div>
	 	<div class="clearfix"></div>
		</li>								
		<li>
		<div class="form_field_left">
			<input type="hidden" autocomplete="off" maxlength="30" id="password1" name="password1" value="<?php echo $pass;?>">
		</div>
		<input type="hidden" autocomplete="off" maxlength="30" id="isAjax" name="isAjax" value="1">

		<div class="clearfix"></div>
		</li>                        

		<li>
			<!-- msz alredy email exist -->
				<span id ="alertMsz" class="errormsz_email"></span>
			<!-- end -->
			<div id="Ajaxloader" style="display:none"><img src="<?php echo $this->getSkinUrl('popup/images/loader.png')?>"/></div>
			<div class="reg_trems">* T & C Apply</div>
			<input type="submit" value="Save" name="register" class="grey-btn" id="formSubmit">
		</li>
	</ul>
</form>
</div>
	<div class="clearfix"></div>

			</div>
		</div>
	</div>
</div> 
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<script type="text/javascript">
jQuery.noConflict();
var customForm = new VarienForm('signup-form');
</script>

<script type="text/javascript">
jQuery.noConflict();
function closeSignup(){
jQuery('#transparent_bg').hide();

}
</script>

<?php
$name = 'popupcookies';     
$value = 'yes'; 
// $getCookies = "";    
$getCookies = Mage::getModel('core/cookie')->get($name);
//$getCookies = "";  
if($getCookies==""){

?>
<script>
jQuery.noConflict();
jQuery(document).ready(function() {
jQuery("#popForm").show();

});
</script>
<?php
Mage::getModel('core/cookie')->set($name, $value);
}
?>

<script>
jQuery.noConflict();
jQuery('#signup-form').submit(function(e){
e.preventDefault();
if (customForm.validator && customForm.validator.validate()){
	jQuery("#Ajaxloader").show();

jQuery.ajax({
//jQuery("#signup-form" ).serialize() ;
type: "POST",
url: "<?php echo Mage::getUrl('customer/account/createpost/'); ?>", // hit action
data : jQuery("#signup-form" ).serialize(),
cache: false,
success : function(msg){
var data = jQuery.parseJSON(msg);
jQuery('#alertMsz').html(data.msg);

if(data.msg=='success'){
	jQuery("#Ajaxloader").hide();
window.location = '<?php echo Mage::getBaseUrl(); ?>';
}
else if(data.msg=='Email already exists'){
	jQuery("#Ajaxloader").hide();
jQuery('.already').html('Email Id already exist');
return false;
}

else{
jQuery('.already').html('Cannot Create Account');
return false;

}

}


});
}               

});
</script>
<?php  
}
}?>
